# Generated by Django 5.2.1 on 2025-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blooddonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=15)),
                ('donation_date', models.CharField(max_length=20)),
            ],
        ),
    ]
